server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: DISCOVER-SERVICE
 tracing:
    sampling:
      probability: 1.0
management:
  tracing:
    sampling:
      probability: 1.0

